Repository AliMD/flight-finder, pull requests merged in 2022-11, with the labels that each got.

#10 fix(crawler): review
  crawler/src/crawl.ts
  crawler/src/lib/type.ts
Labels: enhancement, bugfix

#16 feat(rollup): build config
  pwa/dev-server-dist.mjs
  pwa/global.css
  pwa/index.html
  pwa/manifest.json
  pwa/package.json
  pwa/rollup.config.js
  pwa/rollup.config.mjs
Labels: new-feature

#18 feat(director): job providers
  pwa/config.js
  pwa/index.html
  pwa/package.json
  pwa/src/alwatr-pwa.ts
  pwa/src/component/ionic-components.ts
  pwa/src/component/job-item.ts
  pwa/src/component/page-flight-finder.ts
  pwa/src/director/index.ts
  pwa/src/director/job-add.ts
  pwa/src/director/job-delete.ts
  pwa/src/director/job-list.ts
  pwa/src/type.ts
  yarn.lock
Labels: enhancement, minor, new-feature

#17 fix: review
  .github/workflows/build.yaml
  .vscode/extensions.json
  api/package.json
  api/src/lib/config.ts
  crawler/package.json
  crawler/src/lib/config.ts
  package.json
  pwa/dev-server.mjs
  pwa/manifest.json
  pwa/package.json
  telegram-notifier/package.json
  telegram-notifier/src/lib/config.ts
  yarn.lock
Labels: minor, new-feature

#24 City List Template
  api/demo.http
  api/src/index.ts
  api/src/lib/config.ts
  api/src/route/options.ts
  crawler/src/lib/config.ts
  pwa/global.css
  pwa/src/city-list.ts
  pwa/src/component/job-item.ts
  pwa/src/component/page-flight-finder.ts
  pwa/src/director/index.ts
  pwa/src/director/job-add.ts
  pwa/src/director/job-delete.ts
  pwa/src/director/job-list.ts
  pwa/src/director/toast.ts
  pwa/src/type.ts
  telegram-notifier/src/lib/bot.ts
Labels: enhancement, minor, new-feature

#31 fix: update DocumentObject type
  api/demo.http
  api/package.json
  api/src/lib/type.ts
  api/src/route/job/put.ts
  crawler/package.json
  crawler/src/lib/type.ts
  pwa/package.json
  pwa/src/component/page-flight-finder.ts
  pwa/src/type.ts
  telegram-notifier/package.json
  telegram-notifier/src/bot/command/start.ts
  telegram-notifier/src/lib/type.ts
  yarn.lock
Labels: dependencies

#26 fix(api): handle preflight request
  pwa/src/director/job-add.ts
  pwa/src/director/job-delete.ts
  pwa/src/director/job-list.ts
  telegram-notifier/src/lib/bot.ts
Labels: bugfix

#35 fix: CORS helper
  api/src/index.ts
  api/src/lib/nano-server.ts
  api/src/route/options.ts
Labels: bugfix
