Repository AliMD/flight-finder, pull requests merged in 2022-12, with the labels that each got.

#34 fix: new types and work all services together
  .vscode/extensions.json
  .vscode/settings.json
  api/demo.http
  api/src/index.ts
  api/src/lib/nano-server.ts
  api/src/lib/type.ts
  api/src/route/options.ts
  crawler/src/crawl.ts
  crawler/src/lib/type.ts
  pwa/config.js
  pwa/dev-server.mjs
  pwa/rollup.config.js
  pwa/src/component/job-item.ts
  pwa/src/component/page-flight-finder.ts
  pwa/src/director/job-add.ts
  pwa/src/director/job-delete.ts
  pwa/src/director/job-list.ts
  pwa/src/type.ts
  telegram-notifier/src/lib/bot.ts
  telegram-notifier/src/route/notify.ts
Labels: enhancement, new-feature

#40 PWA localization
  api/package.json
  crawler/package.json
  crawler/yarn.lock
  package.json
  pwa/l10n/fa-IR.json
  pwa/package.json
  pwa/src/alwatr-pwa.ts
  pwa/src/component/job-item.ts
  pwa/src/component/page-flight-finder.ts
  pwa/yarn.lock
  telegram-notifier/package.json
  yarn.lock
Labels: enhancement, new-feature

#30 feat: dockerize services
  .env.example
  api/.dockerignore
  api/Dockerfile
  compose.yml
  crawler/.dockerignore
  crawler/Dockerfile
  pwa/.dockerignore
  pwa/Dockerfile
  pwa/package.json
  telegram-notifier/.dockerignore
  telegram-notifier/Dockerfile
  telegram-notifier/src/lib/storage.ts
Labels: enhancement, major, help-wanted

#53 chore: build configurations
  .eslintignore
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  api/package.json
  api/tsconfig.json
  crawler/package.json
  crawler/tsconfig.json
  package.json
  pwa/dev-server.mjs
  pwa/image/apple-touch-icon.png
  pwa/image/favicon.ico
  pwa/image/icon-192-maskable.png
  pwa/image/icon-192.png
  pwa/image/icon-512-maskable.png
  pwa/image/icon-512.png
  pwa/image/icon.svg
  pwa/index.html
  pwa/manifest.json
  pwa/package.json
  pwa/rollup.config.js
  pwa/src/style/global.css
  pwa/tsconfig.json
  pwa/web-dev-server.config.js
  pwa/workbox-config.js
  telegram-notifier/package.json
  telegram-notifier/tsconfig.json
  yarn.lock
Labels: enhancement, bugfix, new-feature
